moniker: "test.node" # Invent some name you will sure is unique
localhome: "home" # Can be not changed
chainid: "metabelarus.core.cr" # Keep it as it is
mainuser_mnemonic: ".... mnemonic phrase here" # Mmnemonic of your account. This account should have stake currency to run validator.
keyring_pass: "your keyring password" # Invent some password and don't share it with anyone. This is a password for keyring that stars your mnemonic on the server.
ansible_become_password: "yout ansible become password" # Your root or sudo user password on the machine
ansible_user: "root" # Your sudo user on the machine 
seeds: "d6d5f2085565073badf1c811386d96fe72d78029@node-mark.cr.meta-belarus.org:26756"
cert_email: "your@email.com" # your email that the ssl certificate will be linked
domain: "mydomain.cr.meta-belarus.org" # Set your domain name that is linked to the host. Or set localhost when you don't have one.
host_type: "public" # "local" - for testing environments or when the serece has no domain name
source_host: "mark" # Folder name with genesis info
amount_to_delegate: "1000000stake" # Minimal stake to start a validator with an influence