- name: Add global variables
  include_vars:
    file: "{{ playbook_dir }}/config.yml"

- name: Get validator container info
  docker_container_info:
    name: mbcorecr-validator
  register: validator_info
  tags:
    - ubuntu
    - info
    - node
    - validator

- name: Get validator node id
  shell: docker exec -ti mbcorecr-validator sh -c "mbcorecrd tendermint show-node-id"
  register: validator_id
  tags:
    - ubuntu
    - info
    - node
    - validator

- name: Get sentery container info
  docker_container_info:
    name: mbcorecr-sentery
  register: sentery_info
  tags:
    - ubuntu
    - info
    - node
    - sentery

- name: Get sentery id
  shell: docker exec -ti mbcorecr-sentery sh -c "mbcorecrd tendermint show-node-id"
  register: sentery_id
  tags:
    - ubuntu
    - info
    - node
    - sentery

- name: Get seed container info
  docker_container_info:
    name: mbcorecr-seed
  register: seed_info
  ignore_errors: yes
  tags:
    - ubuntu
    - info
    - node
    - seed

- name: Get seed id
  shell: docker exec -ti mbcorecr-seed sh -c "mbcorecrd tendermint show-node-id"
  register: seed_id
  ignore_errors: yes
  tags:
    - ubuntu
    - info
    - node
    - seed

- name: Generate info yml to be fetched
  template:
    src: info.yml
    dest: "{{ project_wrap_dir }}/tmp/info.yml"
  tags:
    - ubuntu
    - info
    - validator
    - sentery
    - seed
    - machine
    - fetch

- name: Fetch info yml
  fetch:
    src: "{{ project_wrap_dir }}/tmp/info.yml"
    dest: "{{ playbook_dir }}/fetched/{{ inventory_hostname }}/"
    flat: true
  tags:
    - ubuntu
    - info
    - machine
    - fetch

- name: Fetch genesis.json
  fetch:
    src: "{{ project_dir }}/build/validator/config/genesis.json"
    dest: "{{ playbook_dir }}/fetched/{{ inventory_hostname }}/"
    flat: true
  tags:
    - ubuntu
    - info
    - machine
    - fetch