// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mbcorecr/invite.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IdentityLevel int32

const (
	IdentityLevel_LevelSuper IdentityLevel = 0
	IdentityLevel_Level0     IdentityLevel = 1
	IdentityLevel_Level1     IdentityLevel = 2
	IdentityLevel_Level2     IdentityLevel = 3
	IdentityLevel_Level3     IdentityLevel = 4
	IdentityLevel_Level4     IdentityLevel = 5
)

var IdentityLevel_name = map[int32]string{
	0: "LevelSuper",
	1: "Level0",
	2: "Level1",
	3: "Level2",
	4: "Level3",
	5: "Level4",
}

var IdentityLevel_value = map[string]int32{
	"LevelSuper": 0,
	"Level0":     1,
	"Level1":     2,
	"Level2":     3,
	"Level3":     4,
	"Level4":     5,
}

func (x IdentityLevel) String() string {
	return proto.EnumName(IdentityLevel_name, int32(x))
}

func (IdentityLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{0}
}

type Invite struct {
	Id           string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Inviter      string        `protobuf:"bytes,2,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee      string        `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	IdentityId   string        `protobuf:"bytes,4,opt,name=identityId,proto3" json:"identityId,omitempty"`
	Level        IdentityLevel `protobuf:"varint,5,opt,name=level,proto3,enum=metabelarus.mbcorecr.mbcorecr.IdentityLevel" json:"level,omitempty"`
	IdentityType IdentityType  `protobuf:"varint,6,opt,name=identityType,proto3,enum=metabelarus.mbcorecr.mbcorecr.IdentityType" json:"identityType,omitempty"`
	Key          string        `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	CreationDt   *time.Time    `protobuf:"bytes,8,opt,name=creationDt,proto3,stdtime" json:"creationDt,omitempty"`
	AcceptanceDt *time.Time    `protobuf:"bytes,9,opt,name=acceptanceDt,proto3,stdtime" json:"acceptanceDt,omitempty"`
}

func (m *Invite) Reset()         { *m = Invite{} }
func (m *Invite) String() string { return proto.CompactTextString(m) }
func (*Invite) ProtoMessage()    {}
func (*Invite) Descriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{0}
}
func (m *Invite) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Invite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Invite.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Invite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invite.Merge(m, src)
}
func (m *Invite) XXX_Size() int {
	return m.Size()
}
func (m *Invite) XXX_DiscardUnknown() {
	xxx_messageInfo_Invite.DiscardUnknown(m)
}

var xxx_messageInfo_Invite proto.InternalMessageInfo

func (m *Invite) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Invite) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *Invite) GetInvitee() string {
	if m != nil {
		return m.Invitee
	}
	return ""
}

func (m *Invite) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *Invite) GetLevel() IdentityLevel {
	if m != nil {
		return m.Level
	}
	return IdentityLevel_LevelSuper
}

func (m *Invite) GetIdentityType() IdentityType {
	if m != nil {
		return m.IdentityType
	}
	return IdentityType_CITIZEN
}

func (m *Invite) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Invite) GetCreationDt() *time.Time {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

func (m *Invite) GetAcceptanceDt() *time.Time {
	if m != nil {
		return m.AcceptanceDt
	}
	return nil
}

type MsgCreateInvite struct {
	Inviter      string        `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Uid          string        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Level        IdentityLevel `protobuf:"varint,3,opt,name=level,proto3,enum=metabelarus.mbcorecr.mbcorecr.IdentityLevel" json:"level,omitempty"`
	IdentityType IdentityType  `protobuf:"varint,4,opt,name=identityType,proto3,enum=metabelarus.mbcorecr.mbcorecr.IdentityType" json:"identityType,omitempty"`
	CreationDt   *time.Time    `protobuf:"bytes,5,opt,name=creationDt,proto3,stdtime" json:"creationDt,omitempty"`
}

func (m *MsgCreateInvite) Reset()         { *m = MsgCreateInvite{} }
func (m *MsgCreateInvite) String() string { return proto.CompactTextString(m) }
func (*MsgCreateInvite) ProtoMessage()    {}
func (*MsgCreateInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{1}
}
func (m *MsgCreateInvite) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateInvite.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateInvite.Merge(m, src)
}
func (m *MsgCreateInvite) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateInvite.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateInvite proto.InternalMessageInfo

func (m *MsgCreateInvite) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *MsgCreateInvite) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MsgCreateInvite) GetLevel() IdentityLevel {
	if m != nil {
		return m.Level
	}
	return IdentityLevel_LevelSuper
}

func (m *MsgCreateInvite) GetIdentityType() IdentityType {
	if m != nil {
		return m.IdentityType
	}
	return IdentityType_CITIZEN
}

func (m *MsgCreateInvite) GetCreationDt() *time.Time {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

type MsgAcceptInvite struct {
	InviteId     string     `protobuf:"bytes,1,opt,name=inviteId,proto3" json:"inviteId,omitempty"`
	Invitee      string     `protobuf:"bytes,2,opt,name=invitee,proto3" json:"invitee,omitempty"`
	Uid          string     `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	AcceptanceDt *time.Time `protobuf:"bytes,4,opt,name=acceptanceDt,proto3,stdtime" json:"acceptanceDt,omitempty"`
}

func (m *MsgAcceptInvite) Reset()         { *m = MsgAcceptInvite{} }
func (m *MsgAcceptInvite) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptInvite) ProtoMessage()    {}
func (*MsgAcceptInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{2}
}
func (m *MsgAcceptInvite) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptInvite.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptInvite.Merge(m, src)
}
func (m *MsgAcceptInvite) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptInvite.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptInvite proto.InternalMessageInfo

func (m *MsgAcceptInvite) GetInviteId() string {
	if m != nil {
		return m.InviteId
	}
	return ""
}

func (m *MsgAcceptInvite) GetInvitee() string {
	if m != nil {
		return m.Invitee
	}
	return ""
}

func (m *MsgAcceptInvite) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MsgAcceptInvite) GetAcceptanceDt() *time.Time {
	if m != nil {
		return m.AcceptanceDt
	}
	return nil
}

type InviteAccount struct {
	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PubKey   string `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	PrivKey  string `protobuf:"bytes,4,opt,name=privKey,proto3" json:"privKey,omitempty"`
	Mnemonic string `protobuf:"bytes,5,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	InviteID string `protobuf:"bytes,6,opt,name=inviteID,proto3" json:"inviteID,omitempty"`
}

func (m *InviteAccount) Reset()         { *m = InviteAccount{} }
func (m *InviteAccount) String() string { return proto.CompactTextString(m) }
func (*InviteAccount) ProtoMessage()    {}
func (*InviteAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{3}
}
func (m *InviteAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InviteAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InviteAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InviteAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteAccount.Merge(m, src)
}
func (m *InviteAccount) XXX_Size() int {
	return m.Size()
}
func (m *InviteAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteAccount.DiscardUnknown(m)
}

var xxx_messageInfo_InviteAccount proto.InternalMessageInfo

func (m *InviteAccount) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *InviteAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InviteAccount) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *InviteAccount) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

func (m *InviteAccount) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

func (m *InviteAccount) GetInviteID() string {
	if m != nil {
		return m.InviteID
	}
	return ""
}

type MsgCancelInvite struct {
	Inviter  string `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Sequence string `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgCancelInvite) Reset()         { *m = MsgCancelInvite{} }
func (m *MsgCancelInvite) String() string { return proto.CompactTextString(m) }
func (*MsgCancelInvite) ProtoMessage()    {}
func (*MsgCancelInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_60b07f1de3d385de, []int{4}
}
func (m *MsgCancelInvite) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelInvite.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelInvite.Merge(m, src)
}
func (m *MsgCancelInvite) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelInvite.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelInvite proto.InternalMessageInfo

func (m *MsgCancelInvite) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *MsgCancelInvite) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func init() {
	proto.RegisterEnum("metabelarus.mbcorecr.mbcorecr.IdentityLevel", IdentityLevel_name, IdentityLevel_value)
	proto.RegisterType((*Invite)(nil), "metabelarus.mbcorecr.mbcorecr.Invite")
	proto.RegisterType((*MsgCreateInvite)(nil), "metabelarus.mbcorecr.mbcorecr.MsgCreateInvite")
	proto.RegisterType((*MsgAcceptInvite)(nil), "metabelarus.mbcorecr.mbcorecr.MsgAcceptInvite")
	proto.RegisterType((*InviteAccount)(nil), "metabelarus.mbcorecr.mbcorecr.InviteAccount")
	proto.RegisterType((*MsgCancelInvite)(nil), "metabelarus.mbcorecr.mbcorecr.MsgCancelInvite")
}

func init() { proto.RegisterFile("mbcorecr/invite.proto", fileDescriptor_60b07f1de3d385de) }

var fileDescriptor_60b07f1de3d385de = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc9, 0x8e, 0xd3, 0x40,
	0x10, 0x86, 0xd3, 0x76, 0xd6, 0x62, 0x26, 0x58, 0x2d, 0x16, 0x2b, 0x12, 0x9e, 0x28, 0xa7, 0x08,
	0x90, 0x3d, 0x64, 0x78, 0x00, 0x26, 0x44, 0x42, 0x61, 0x11, 0x52, 0x98, 0x13, 0x9c, 0xbc, 0x14,
	0xc6, 0x22, 0x5e, 0xb0, 0xdb, 0x11, 0x79, 0x8b, 0x39, 0x70, 0xe3, 0xc0, 0x89, 0x77, 0xe1, 0x38,
	0x47, 0x6e, 0xa0, 0xe4, 0x45, 0x90, 0xdb, 0x6e, 0x2f, 0x1c, 0x60, 0x58, 0x6e, 0x7f, 0x75, 0xf9,
	0xaf, 0x2e, 0x7f, 0x55, 0x36, 0x5c, 0xf7, 0x2d, 0x3b, 0x8c, 0xd1, 0x8e, 0x0d, 0x2f, 0xd8, 0x78,
	0x0c, 0xf5, 0x28, 0x0e, 0x59, 0x48, 0x6f, 0xf9, 0xc8, 0x4c, 0x0b, 0xd7, 0x66, 0x9c, 0x26, 0xba,
	0x78, 0xa4, 0x14, 0xa3, 0x9b, 0x95, 0xcb, 0xc1, 0x80, 0x79, 0x6c, 0x9b, 0xfb, 0x46, 0xd7, 0xdc,
	0xd0, 0x0d, 0xb9, 0x34, 0x32, 0x55, 0x9c, 0x1e, 0xb9, 0x61, 0xe8, 0xae, 0xd1, 0xe0, 0x91, 0x95,
	0xbe, 0x36, 0x98, 0xe7, 0x63, 0xc2, 0x4c, 0x3f, 0xca, 0x1f, 0x98, 0x7c, 0x94, 0xa1, 0xbb, 0xe4,
	0xf7, 0xd3, 0x21, 0x48, 0x9e, 0xa3, 0x92, 0x31, 0x99, 0x0e, 0x56, 0x92, 0xe7, 0x50, 0x15, 0x7a,
	0x79, 0x67, 0xb1, 0x2a, 0xf1, 0x43, 0x11, 0x56, 0x19, 0x54, 0xe5, 0x7a, 0x06, 0xa9, 0x06, 0x20,
	0xfa, 0x5a, 0x3a, 0x6a, 0x9b, 0x27, 0x6b, 0x27, 0x74, 0x0e, 0x9d, 0x35, 0x6e, 0x70, 0xad, 0x76,
	0xc6, 0x64, 0x3a, 0x9c, 0xdd, 0xd5, 0x7f, 0xf9, 0xb6, 0xfa, 0xb2, 0x70, 0x3e, 0xcd, 0x3c, 0xab,
	0xdc, 0x4a, 0x9f, 0xc3, 0x81, 0xa8, 0x78, 0xb6, 0x8d, 0x50, 0xed, 0xf2, 0x52, 0x77, 0x2e, 0x59,
	0x2a, 0xb3, 0xac, 0x1a, 0x05, 0xa8, 0x02, 0xf2, 0x5b, 0xdc, 0xaa, 0x3d, 0xde, 0x6d, 0x26, 0xe9,
	0x03, 0x00, 0x3b, 0x46, 0x93, 0x79, 0x61, 0xb0, 0x60, 0x6a, 0x7f, 0x4c, 0xa6, 0x57, 0x66, 0x23,
	0x3d, 0x67, 0xa9, 0x0b, 0x96, 0xfa, 0x99, 0x60, 0x39, 0x6f, 0x9f, 0x7f, 0x3b, 0x22, 0xab, 0x9a,
	0x87, 0x2e, 0xe0, 0xc0, 0xb4, 0x6d, 0x8c, 0x98, 0x19, 0xd8, 0xb8, 0x60, 0xea, 0xe0, 0x92, 0x35,
	0x1a, 0xae, 0xc9, 0x07, 0x09, 0xae, 0x3e, 0x4b, 0xdc, 0x87, 0x59, 0x5d, 0x2c, 0xc6, 0x54, 0x1b,
	0x0b, 0x69, 0x8e, 0x45, 0x01, 0x39, 0xf5, 0x9c, 0x62, 0x58, 0x99, 0xac, 0x70, 0xcb, 0xff, 0x0f,
	0x77, 0xfb, 0x5f, 0x71, 0x37, 0xe1, 0x76, 0xfe, 0x1c, 0xee, 0xe4, 0x13, 0xe1, 0x58, 0x4e, 0x39,
	0xaa, 0x02, 0xcb, 0x08, 0xfa, 0x39, 0x87, 0xa5, 0xd8, 0xe1, 0x32, 0xae, 0xef, 0xab, 0xd4, 0xdc,
	0xd7, 0x02, 0x99, 0x5c, 0x21, 0xfb, 0x79, 0x70, 0xed, 0xbf, 0x1a, 0xdc, 0x67, 0x02, 0x87, 0x79,
	0x63, 0xa7, 0xb6, 0x1d, 0xa6, 0x01, 0x13, 0x37, 0x91, 0xea, 0x26, 0x15, 0x7a, 0xa6, 0xe3, 0xc4,
	0x98, 0x24, 0xa2, 0xab, 0x22, 0xa4, 0x37, 0xa0, 0x1b, 0xa5, 0xd6, 0x13, 0xdc, 0x16, 0x8d, 0x15,
	0x51, 0xe6, 0x88, 0x62, 0x6f, 0x93, 0x25, 0xf2, 0x4f, 0x4b, 0x84, 0xd9, 0xdb, 0xfb, 0x01, 0xfa,
	0x61, 0xe0, 0xd9, 0x9c, 0xe8, 0x60, 0x55, 0xc6, 0x35, 0x32, 0x0b, 0xfe, 0xad, 0x54, 0x64, 0x16,
	0x93, 0x47, 0xf9, 0x7e, 0x65, 0x5d, 0xaf, 0x7f, 0xbb, 0x5f, 0x23, 0xe8, 0x27, 0xf8, 0x2e, 0xc5,
	0xc0, 0x16, 0x1c, 0xcb, 0xf8, 0xf6, 0x2b, 0x38, 0x6c, 0x6c, 0x0f, 0x1d, 0x02, 0x70, 0xf1, 0x22,
	0x8d, 0x30, 0x56, 0x5a, 0x14, 0xa0, 0xcb, 0xe3, 0x63, 0x85, 0x94, 0xfa, 0x9e, 0x22, 0x95, 0x7a,
	0xa6, 0xc8, 0xa5, 0x3e, 0x51, 0xda, 0xa5, 0xbe, 0xaf, 0x74, 0xe6, 0x8f, 0xbf, 0xec, 0x34, 0x72,
	0xb1, 0xd3, 0xc8, 0xf7, 0x9d, 0x46, 0xce, 0xf7, 0x5a, 0xeb, 0x62, 0xaf, 0xb5, 0xbe, 0xee, 0xb5,
	0xd6, 0xcb, 0x63, 0xd7, 0x63, 0x6f, 0x52, 0x4b, 0xb7, 0x43, 0xdf, 0xa8, 0x2d, 0xa4, 0x51, 0xfe,
	0x25, 0xdf, 0x57, 0x92, 0x6d, 0x23, 0x4c, 0xac, 0x2e, 0x9f, 0xe0, 0xc9, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xec, 0xb1, 0x53, 0x11, 0x7f, 0x05, 0x00, 0x00,
}

func (m *Invite) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Invite) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Invite) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AcceptanceDt != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.AcceptanceDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.AcceptanceDt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintInvite(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreationDt != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintInvite(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x3a
	}
	if m.IdentityType != 0 {
		i = encodeVarintInvite(dAtA, i, uint64(m.IdentityType))
		i--
		dAtA[i] = 0x30
	}
	if m.Level != 0 {
		i = encodeVarintInvite(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x28
	}
	if len(m.IdentityId) > 0 {
		i -= len(m.IdentityId)
		copy(dAtA[i:], m.IdentityId)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.IdentityId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invitee) > 0 {
		i -= len(m.Invitee)
		copy(dAtA[i:], m.Invitee)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Invitee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateInvite) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateInvite) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateInvite) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationDt != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintInvite(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x2a
	}
	if m.IdentityType != 0 {
		i = encodeVarintInvite(dAtA, i, uint64(m.IdentityType))
		i--
		dAtA[i] = 0x20
	}
	if m.Level != 0 {
		i = encodeVarintInvite(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptInvite) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptInvite) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptInvite) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AcceptanceDt != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.AcceptanceDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.AcceptanceDt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintInvite(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Invitee) > 0 {
		i -= len(m.Invitee)
		copy(dAtA[i:], m.Invitee)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Invitee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.InviteId) > 0 {
		i -= len(m.InviteId)
		copy(dAtA[i:], m.InviteId)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.InviteId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InviteAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InviteAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InviteAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InviteID) > 0 {
		i -= len(m.InviteID)
		copy(dAtA[i:], m.InviteID)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.InviteID)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Mnemonic) > 0 {
		i -= len(m.Mnemonic)
		copy(dAtA[i:], m.Mnemonic)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Mnemonic)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PrivKey) > 0 {
		i -= len(m.PrivKey)
		copy(dAtA[i:], m.PrivKey)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.PrivKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelInvite) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelInvite) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelInvite) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequence) > 0 {
		i -= len(m.Sequence)
		copy(dAtA[i:], m.Sequence)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Sequence)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintInvite(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintInvite(dAtA []byte, offset int, v uint64) int {
	offset -= sovInvite(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Invite) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Invitee)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.IdentityId)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	if m.Level != 0 {
		n += 1 + sovInvite(uint64(m.Level))
	}
	if m.IdentityType != 0 {
		n += 1 + sovInvite(uint64(m.IdentityType))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	if m.CreationDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt)
		n += 1 + l + sovInvite(uint64(l))
	}
	if m.AcceptanceDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.AcceptanceDt)
		n += 1 + l + sovInvite(uint64(l))
	}
	return n
}

func (m *MsgCreateInvite) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	if m.Level != 0 {
		n += 1 + sovInvite(uint64(m.Level))
	}
	if m.IdentityType != 0 {
		n += 1 + sovInvite(uint64(m.IdentityType))
	}
	if m.CreationDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt)
		n += 1 + l + sovInvite(uint64(l))
	}
	return n
}

func (m *MsgAcceptInvite) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InviteId)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Invitee)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	if m.AcceptanceDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.AcceptanceDt)
		n += 1 + l + sovInvite(uint64(l))
	}
	return n
}

func (m *InviteAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.PrivKey)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Mnemonic)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.InviteID)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	return n
}

func (m *MsgCancelInvite) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	l = len(m.Sequence)
	if l > 0 {
		n += 1 + l + sovInvite(uint64(l))
	}
	return n
}

func sovInvite(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInvite(x uint64) (n int) {
	return sovInvite(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Invite) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Invite: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Invite: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= IdentityLevel(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityType", wireType)
			}
			m.IdentityType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdentityType |= IdentityType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationDt == nil {
				m.CreationDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptanceDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AcceptanceDt == nil {
				m.AcceptanceDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.AcceptanceDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateInvite) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateInvite: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateInvite: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= IdentityLevel(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityType", wireType)
			}
			m.IdentityType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdentityType |= IdentityType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationDt == nil {
				m.CreationDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptInvite) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptInvite: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptInvite: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InviteId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InviteId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptanceDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AcceptanceDt == nil {
				m.AcceptanceDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.AcceptanceDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InviteAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InviteAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InviteAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mnemonic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mnemonic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InviteID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InviteID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelInvite) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelInvite: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelInvite: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequence = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInvite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInvite(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInvite
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInvite
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInvite
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInvite
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInvite        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInvite          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInvite = fmt.Errorf("proto: unexpected end of group")
)
