- name: Add global variables
  include_vars:
    file: "{{ playbook_dir }}/config.yml"
  tags:
    - configs

- name: Fake init node to avoid local bugs
  shell:
    cmd: "{{ project_dir }}/build/mbcorecrd init test --chain-id test --overwrite"
    chdir: "{{ project_dir }}"
  tags:
    - init
    - ubuntu

- name: Cleanup home folder
  file:
    state: absent
    path: "{{ project_dir }}/build/{{ item }}"
  with_items:
    - validator
    - sentery
    - seed
  tags:
    - init
    - ubuntu
    - cleanup

- name: Init node
  shell:
    cmd: |
      {{ project_dir }}/build/mbcorecrd init {{ moniker }}.{{ item }} \
      --chain-id {{ chainid }} --overwrite \
      --home {{ project_dir }}/build/{{ item }}
    chdir: "{{ project_dir }}"
  with_items:
    - validator
    - sentery
    - seed
  tags:
    - init
    - ubuntu

- name: Init chain node with configs
  template:
    src: "{{ playbook_dir }}/templates/{{ item.file }}"
    dest: "{{ project_dir }}/build/{{item.folder}}/config/{{ item.file }}"
  vars:
    template_node: "{{ item.vars }}"
    template_port: "{{ seed_export.p2p_port if item.folder == 'seed' else sentery_node.p2p_port }}"
    template_alias: "{{ item.folder }}"
  with_items: 
    - file: app.toml
      folder: validator
      vars: "{{ validator_node }}"
    - file: config.toml
      folder: validator
      vars: "{{ validator_node }}"
    - file: app.toml
      folder: sentery
      vars: "{{ sentery_node }}"
    - file: config.toml
      folder: sentery
      vars: "{{ sentery_node }}"
    - file: app.toml
      folder: seed
      vars: "{{ seed_node }}"
    - file: config.toml
      folder: seed
      vars: "{{ seed_node }}"
  tags:
    - init
    - ubuntu
    - configs

- name: Setup sertificate
  copy:
    src: "/etc/letsencrypt/live/{{ domain }}.tcp/{{ item.cert }}"
    remote_src: yes
    dest: "{{ project_dir }}/build/{{ item.node }}/config/{{ item.cert }}"
  with_items:
    - node: validator
      cert: cert.pem
    - node: validator
      cert: privkey.pem
    - node: sentery
      cert: cert.pem
    - node: sentery
      cert: privkey.pem
    - node: seed
      cert: cert.pem
    - node: seed
      cert: privkey.pem
  when: host_type == "public"
  tags:
    - init
    - ubuntu
    - configs