// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crconsent/request.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ServicePermissions int32

const (
	// Access to unlock records in passport
	ServicePermissions_ALLOW_RECORD_UNLOCK ServicePermissions = 0
	// Access to delete records from passport
	ServicePermissions_ALLOW_RECORD_DELETE ServicePermissions = 1
	// Access to generate new invite
	ServicePermissions_ALLOW_INVITE_GENERATION ServicePermissions = 2
	// Access to issue passport refresh
	ServicePermissions_ALLOW_REFRESH_GENERATION ServicePermissions = 3
	// Write access to services passport without auth
	ServicePermissions_ALLOW_SERVICES_WRITE ServicePermissions = 4
	// Write access to cietizens passport without auth
	ServicePermissions_ALLOW_CITIZEN_WRITE ServicePermissions = 5
	// Write access to residents passport without auth
	ServicePermissions_ALLOW_RESIDENT_WRITE ServicePermissions = 6
)

var ServicePermissions_name = map[int32]string{
	0: "ALLOW_RECORD_UNLOCK",
	1: "ALLOW_RECORD_DELETE",
	2: "ALLOW_INVITE_GENERATION",
	3: "ALLOW_REFRESH_GENERATION",
	4: "ALLOW_SERVICES_WRITE",
	5: "ALLOW_CITIZEN_WRITE",
	6: "ALLOW_RESIDENT_WRITE",
}

var ServicePermissions_value = map[string]int32{
	"ALLOW_RECORD_UNLOCK":      0,
	"ALLOW_RECORD_DELETE":      1,
	"ALLOW_INVITE_GENERATION":  2,
	"ALLOW_REFRESH_GENERATION": 3,
	"ALLOW_SERVICES_WRITE":     4,
	"ALLOW_CITIZEN_WRITE":      5,
	"ALLOW_RESIDENT_WRITE":     6,
}

func (x ServicePermissions) String() string {
	return proto.EnumName(ServicePermissions_name, int32(x))
}

func (ServicePermissions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{0}
}

type RequestType int32

const (
	RequestType_INVITE_PACK  RequestType = 0
	RequestType_APPROVE_PACK RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "INVITE_PACK",
	1: "APPROVE_PACK",
}

var RequestType_value = map[string]int32{
	"INVITE_PACK":  0,
	"APPROVE_PACK": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{1}
}

type Status int32

const (
	Status_ISSUED   Status = 0
	Status_REJECTED Status = 1
	Status_ACCEPTED Status = 2
)

var Status_name = map[int32]string{
	0: "ISSUED",
	1: "REJECTED",
	2: "ACCEPTED",
}

var Status_value = map[string]int32{
	"ISSUED":   0,
	"REJECTED": 1,
	"ACCEPTED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{2}
}

type Request struct {
	// Request creator id
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	//
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	//
	Initiator string `protobuf:"bytes,3,opt,name=initiator,proto3" json:"initiator,omitempty"`
	// Request recipient id
	Recipient string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Type of request
	RequestType RequestType `protobuf:"varint,5,opt,name=requestType,proto3,enum=metabelarus.mbcorecr.crconsent.RequestType" json:"requestType,omitempty"`
	// Request status
	Status Status `protobuf:"varint,6,opt,name=status,proto3,enum=metabelarus.mbcorecr.crconsent.Status" json:"status,omitempty"`
	//
	Value int32 `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	//
	Memo string `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	// Link to request external description
	PromoUrl string `protobuf:"bytes,9,opt,name=promoUrl,proto3" json:"promoUrl,omitempty"`
	// Date request created
	CreationDt *time.Time `protobuf:"bytes,10,opt,name=creationDt,proto3,stdtime" json:"creationDt,omitempty"`
	// Request expiration date
	FinalDt *time.Time `protobuf:"bytes,11,opt,name=finalDt,proto3,stdtime" json:"finalDt,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return m.Size()
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *Request) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Request) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_INVITE_PACK
}

func (m *Request) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ISSUED
}

func (m *Request) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Request) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Request) GetPromoUrl() string {
	if m != nil {
		return m.PromoUrl
	}
	return ""
}

func (m *Request) GetCreationDt() *time.Time {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

func (m *Request) GetFinalDt() *time.Time {
	if m != nil {
		return m.FinalDt
	}
	return nil
}

type MsgCreateRequest struct {
	Creator     string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Initiator   string      `protobuf:"bytes,2,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Recipient   string      `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	RequestType RequestType `protobuf:"varint,4,opt,name=requestType,proto3,enum=metabelarus.mbcorecr.crconsent.RequestType" json:"requestType,omitempty"`
	Status      Status      `protobuf:"varint,5,opt,name=status,proto3,enum=metabelarus.mbcorecr.crconsent.Status" json:"status,omitempty"`
	Value       int32       `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Memo        string      `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	PromoUrl    string      `protobuf:"bytes,8,opt,name=promoUrl,proto3" json:"promoUrl,omitempty"`
	CreationDt  *time.Time  `protobuf:"bytes,10,opt,name=creationDt,proto3,stdtime" json:"creationDt,omitempty"`
	FinalDt     *time.Time  `protobuf:"bytes,11,opt,name=finalDt,proto3,stdtime" json:"finalDt,omitempty"`
}

func (m *MsgCreateRequest) Reset()         { *m = MsgCreateRequest{} }
func (m *MsgCreateRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRequest) ProtoMessage()    {}
func (*MsgCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{1}
}
func (m *MsgCreateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRequest.Merge(m, src)
}
func (m *MsgCreateRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRequest proto.InternalMessageInfo

func (m *MsgCreateRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRequest) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *MsgCreateRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgCreateRequest) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_INVITE_PACK
}

func (m *MsgCreateRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ISSUED
}

func (m *MsgCreateRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MsgCreateRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *MsgCreateRequest) GetPromoUrl() string {
	if m != nil {
		return m.PromoUrl
	}
	return ""
}

func (m *MsgCreateRequest) GetCreationDt() *time.Time {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

func (m *MsgCreateRequest) GetFinalDt() *time.Time {
	if m != nil {
		return m.FinalDt
	}
	return nil
}

type MsgUpdateRequest struct {
	Creator     string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id          string      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Initiator   string      `protobuf:"bytes,3,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Recipient   string      `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	RequestType RequestType `protobuf:"varint,5,opt,name=requestType,proto3,enum=metabelarus.mbcorecr.crconsent.RequestType" json:"requestType,omitempty"`
	Status      Status      `protobuf:"varint,6,opt,name=status,proto3,enum=metabelarus.mbcorecr.crconsent.Status" json:"status,omitempty"`
	Value       int32       `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	Memo        string      `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	PromoUrl    string      `protobuf:"bytes,9,opt,name=promoUrl,proto3" json:"promoUrl,omitempty"`
	CreationDt  *time.Time  `protobuf:"bytes,10,opt,name=creationDt,proto3,stdtime" json:"creationDt,omitempty"`
	FinalDt     *time.Time  `protobuf:"bytes,11,opt,name=finalDt,proto3,stdtime" json:"finalDt,omitempty"`
}

func (m *MsgUpdateRequest) Reset()         { *m = MsgUpdateRequest{} }
func (m *MsgUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRequest) ProtoMessage()    {}
func (*MsgUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447d003a5a80b564, []int{2}
}
func (m *MsgUpdateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRequest.Merge(m, src)
}
func (m *MsgUpdateRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRequest proto.InternalMessageInfo

func (m *MsgUpdateRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgUpdateRequest) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *MsgUpdateRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgUpdateRequest) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_INVITE_PACK
}

func (m *MsgUpdateRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ISSUED
}

func (m *MsgUpdateRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MsgUpdateRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *MsgUpdateRequest) GetPromoUrl() string {
	if m != nil {
		return m.PromoUrl
	}
	return ""
}

func (m *MsgUpdateRequest) GetCreationDt() *time.Time {
	if m != nil {
		return m.CreationDt
	}
	return nil
}

func (m *MsgUpdateRequest) GetFinalDt() *time.Time {
	if m != nil {
		return m.FinalDt
	}
	return nil
}

func init() {
	proto.RegisterEnum("metabelarus.mbcorecr.crconsent.ServicePermissions", ServicePermissions_name, ServicePermissions_value)
	proto.RegisterEnum("metabelarus.mbcorecr.crconsent.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("metabelarus.mbcorecr.crconsent.Status", Status_name, Status_value)
	proto.RegisterType((*Request)(nil), "metabelarus.mbcorecr.crconsent.Request")
	proto.RegisterType((*MsgCreateRequest)(nil), "metabelarus.mbcorecr.crconsent.MsgCreateRequest")
	proto.RegisterType((*MsgUpdateRequest)(nil), "metabelarus.mbcorecr.crconsent.MsgUpdateRequest")
}

func init() { proto.RegisterFile("crconsent/request.proto", fileDescriptor_447d003a5a80b564) }

var fileDescriptor_447d003a5a80b564 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x95, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xe3, 0xfc, 0x71, 0xd2, 0x49, 0xd5, 0xd7, 0xda, 0xb7, 0x52, 0xad, 0x50, 0xb9, 0x51,
	0x0f, 0x28, 0x2a, 0x92, 0x5d, 0xca, 0x8d, 0x03, 0x22, 0xb5, 0x17, 0x30, 0x4d, 0x93, 0x68, 0xed,
	0xb4, 0x52, 0x2f, 0x91, 0xe3, 0x6e, 0xc3, 0x4a, 0xb1, 0xd7, 0xd8, 0x9b, 0x8a, 0x7e, 0x8b, 0x7e,
	0x1f, 0x6e, 0x9c, 0x90, 0x90, 0x50, 0x8f, 0xdc, 0x40, 0xed, 0x17, 0x41, 0xb1, 0x93, 0x26, 0x08,
	0x68, 0x2b, 0xc1, 0xa1, 0x07, 0x6e, 0x9e, 0x79, 0xe6, 0xd9, 0xdd, 0x99, 0xdf, 0xae, 0x0c, 0x6b,
	0x7e, 0xec, 0xf3, 0x30, 0xa1, 0xa1, 0x30, 0x62, 0xfa, 0x76, 0x4c, 0x13, 0xa1, 0x47, 0x31, 0x17,
	0x1c, 0x69, 0x01, 0x15, 0xde, 0x80, 0x8e, 0xbc, 0x78, 0x9c, 0xe8, 0xc1, 0xc0, 0xe7, 0x31, 0xf5,
	0x63, 0xfd, 0xba, 0xba, 0xb6, 0x3a, 0xe4, 0x43, 0x9e, 0x96, 0x1a, 0x93, 0xaf, 0xcc, 0x55, 0xdb,
	0x18, 0x72, 0x3e, 0x1c, 0x51, 0x23, 0x8d, 0x06, 0xe3, 0x13, 0x43, 0xb0, 0x80, 0x26, 0xc2, 0x0b,
	0xa2, 0xac, 0x60, 0xf3, 0x43, 0x01, 0xca, 0x24, 0xdb, 0x08, 0xa9, 0x50, 0xf6, 0x63, 0xea, 0x09,
	0x1e, 0xab, 0x52, 0x5d, 0x6a, 0x2c, 0x91, 0x59, 0x88, 0x56, 0x20, 0xcf, 0x8e, 0xd5, 0x7c, 0x9a,
	0xcc, 0xb3, 0x63, 0xb4, 0x0e, 0x4b, 0x2c, 0x64, 0x82, 0xa5, 0xb5, 0x85, 0x34, 0x3d, 0x4f, 0x4c,
	0xd4, 0x98, 0xfa, 0x2c, 0x62, 0x34, 0x14, 0x6a, 0x31, 0x53, 0xaf, 0x13, 0x68, 0x1f, 0xaa, 0xd3,
	0xce, 0xdc, 0xb3, 0x88, 0xaa, 0xa5, 0xba, 0xd4, 0x58, 0xd9, 0x79, 0xa4, 0xdf, 0xdc, 0x9e, 0x4e,
	0xe6, 0x16, 0xb2, 0xe8, 0x47, 0xcf, 0x40, 0x4e, 0x84, 0x27, 0xc6, 0x89, 0x2a, 0xa7, 0x2b, 0x3d,
	0xbc, 0x6d, 0x25, 0x27, 0xad, 0x26, 0x53, 0x17, 0x5a, 0x85, 0xd2, 0xa9, 0x37, 0x1a, 0x53, 0xb5,
	0x5c, 0x97, 0x1a, 0x25, 0x92, 0x05, 0x08, 0x41, 0x31, 0xa0, 0x01, 0x57, 0x2b, 0xe9, 0xe9, 0xd3,
	0x6f, 0x54, 0x83, 0x4a, 0x14, 0xf3, 0x80, 0xf7, 0xe2, 0x91, 0xba, 0x94, 0xe6, 0xaf, 0x63, 0xf4,
	0x1c, 0x20, 0x9d, 0x15, 0xe3, 0xa1, 0x25, 0x54, 0xa8, 0x4b, 0x8d, 0xea, 0x4e, 0x4d, 0xcf, 0x86,
	0xaf, 0xcf, 0x86, 0xaf, 0xbb, 0xb3, 0xe1, 0xef, 0x16, 0xcf, 0xbf, 0x6e, 0x48, 0x64, 0xc1, 0x83,
	0x9e, 0x42, 0xf9, 0x84, 0x85, 0xde, 0xc8, 0x12, 0x6a, 0xf5, 0x8e, 0xf6, 0x99, 0x61, 0xf3, 0x7d,
	0x01, 0x94, 0xfd, 0x64, 0x68, 0x4e, 0x56, 0xa3, 0xb7, 0xd3, 0xfc, 0x81, 0x5e, 0xfe, 0x46, 0x7a,
	0x85, 0x5b, 0xe8, 0x15, 0xff, 0x1a, 0xbd, 0xd2, 0x9f, 0xd1, 0x93, 0x7f, 0x45, 0xaf, 0xfc, 0x1b,
	0x7a, 0x95, 0x7b, 0x45, 0xef, 0x53, 0x46, 0xaf, 0x17, 0x1d, 0xdf, 0x89, 0xde, 0xbf, 0xb7, 0x78,
	0x9f, 0xdf, 0xe2, 0xd6, 0x67, 0x09, 0x90, 0x43, 0xe3, 0x53, 0xe6, 0xd3, 0x2e, 0x8d, 0x03, 0x96,
	0x24, 0x8c, 0x87, 0x09, 0x5a, 0x83, 0xff, 0x9b, 0xad, 0x56, 0xe7, 0xb0, 0x4f, 0xb0, 0xd9, 0x21,
	0x56, 0xbf, 0xd7, 0x6e, 0x75, 0xcc, 0x3d, 0x25, 0xf7, 0x93, 0x60, 0xe1, 0x16, 0x76, 0xb1, 0x22,
	0xa1, 0x07, 0xb0, 0x96, 0x09, 0x76, 0xfb, 0xc0, 0x76, 0x71, 0xff, 0x25, 0x6e, 0x63, 0xd2, 0x74,
	0xed, 0x4e, 0x5b, 0xc9, 0xa3, 0x75, 0x50, 0x67, 0xae, 0x17, 0x04, 0x3b, 0xaf, 0x16, 0xd5, 0x02,
	0x52, 0x61, 0x35, 0x53, 0x1d, 0x4c, 0x0e, 0x6c, 0x13, 0x3b, 0xfd, 0x43, 0x62, 0xbb, 0x58, 0x29,
	0xce, 0x77, 0x33, 0x6d, 0xd7, 0x3e, 0xc2, 0xed, 0xa9, 0x50, 0x9a, 0x5b, 0x08, 0x76, 0x6c, 0x0b,
	0xb7, 0xdd, 0xa9, 0x22, 0x6f, 0x6d, 0x43, 0x75, 0x01, 0x38, 0xfa, 0x0f, 0xaa, 0xd3, 0x03, 0x75,
	0x9b, 0x69, 0x03, 0x0a, 0x2c, 0x37, 0xbb, 0x5d, 0xd2, 0x39, 0x98, 0x66, 0xa4, 0xad, 0x6d, 0x90,
	0x33, 0xb0, 0x08, 0x40, 0xb6, 0x1d, 0xa7, 0x87, 0x2d, 0x25, 0x87, 0x96, 0xa1, 0x42, 0xf0, 0x6b,
	0x6c, 0xba, 0xd8, 0x52, 0xa4, 0x49, 0xd4, 0x34, 0x4d, 0xdc, 0x9d, 0x44, 0xf9, 0xdd, 0xbd, 0x8f,
	0x97, 0x9a, 0x74, 0x71, 0xa9, 0x49, 0xdf, 0x2e, 0x35, 0xe9, 0xfc, 0x4a, 0xcb, 0x5d, 0x5c, 0x69,
	0xb9, 0x2f, 0x57, 0x5a, 0xee, 0xe8, 0xf1, 0x90, 0x89, 0x37, 0xe3, 0x81, 0xee, 0xf3, 0xc0, 0x58,
	0xb8, 0x4c, 0xc6, 0xec, 0x32, 0x19, 0xef, 0x8c, 0xf9, 0x1f, 0x53, 0x9c, 0x45, 0x34, 0x19, 0xc8,
	0x29, 0xa4, 0x27, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x45, 0x3e, 0xe3, 0x3b, 0x4b, 0x07, 0x00,
	0x00,
}

func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalDt != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.FinalDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintRequest(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreationDt != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintRequest(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x52
	}
	if len(m.PromoUrl) > 0 {
		i -= len(m.PromoUrl)
		copy(dAtA[i:], m.PromoUrl)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.PromoUrl)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x42
	}
	if m.Value != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.RequestType != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.RequestType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Initiator) > 0 {
		i -= len(m.Initiator)
		copy(dAtA[i:], m.Initiator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Initiator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalDt != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.FinalDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintRequest(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreationDt != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintRequest(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x52
	}
	if len(m.PromoUrl) > 0 {
		i -= len(m.PromoUrl)
		copy(dAtA[i:], m.PromoUrl)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.PromoUrl)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Value != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.RequestType != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.RequestType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Initiator) > 0 {
		i -= len(m.Initiator)
		copy(dAtA[i:], m.Initiator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Initiator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalDt != nil {
		n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.FinalDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintRequest(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreationDt != nil {
		n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationDt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintRequest(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x52
	}
	if len(m.PromoUrl) > 0 {
		i -= len(m.PromoUrl)
		copy(dAtA[i:], m.PromoUrl)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.PromoUrl)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x42
	}
	if m.Value != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.RequestType != 0 {
		i = encodeVarintRequest(dAtA, i, uint64(m.RequestType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Initiator) > 0 {
		i -= len(m.Initiator)
		copy(dAtA[i:], m.Initiator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Initiator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Initiator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.RequestType != 0 {
		n += 1 + sovRequest(uint64(m.RequestType))
	}
	if m.Status != 0 {
		n += 1 + sovRequest(uint64(m.Status))
	}
	if m.Value != 0 {
		n += 1 + sovRequest(uint64(m.Value))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.PromoUrl)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.CreationDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.FinalDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	return n
}

func (m *MsgCreateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Initiator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.RequestType != 0 {
		n += 1 + sovRequest(uint64(m.RequestType))
	}
	if m.Status != 0 {
		n += 1 + sovRequest(uint64(m.Status))
	}
	if m.Value != 0 {
		n += 1 + sovRequest(uint64(m.Value))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.PromoUrl)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.CreationDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.FinalDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	return n
}

func (m *MsgUpdateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Initiator)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.RequestType != 0 {
		n += 1 + sovRequest(uint64(m.RequestType))
	}
	if m.Status != 0 {
		n += 1 + sovRequest(uint64(m.Status))
	}
	if m.Value != 0 {
		n += 1 + sovRequest(uint64(m.Value))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.PromoUrl)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.CreationDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	if m.FinalDt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.FinalDt)
		n += 1 + l + sovRequest(uint64(l))
	}
	return n
}

func sovRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRequest(x uint64) (n int) {
	return sovRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initiator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Initiator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromoUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PromoUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationDt == nil {
				m.CreationDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FinalDt == nil {
				m.FinalDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.FinalDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initiator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Initiator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromoUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PromoUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationDt == nil {
				m.CreationDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FinalDt == nil {
				m.FinalDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.FinalDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initiator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Initiator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromoUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PromoUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationDt == nil {
				m.CreationDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalDt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FinalDt == nil {
				m.FinalDt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.FinalDt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRequest = fmt.Errorf("proto: unexpected end of group")
)
