- name: Add global variables
  include_vars:
    file: "{{ playbook_dir }}/config.yml"
  tags:
    - valinit
    - ubnutu
    - configs

- name: Add main user creation script
  template:
    src: "mainuser.sh"
    dest: "{{ project_dir }}/build/validator/mainuser.sh"
    mode: '755'
  tags:
    - valinit
    - ubnutu
    - register

- name: Register validator account
  expect:
    command: |
      docker exec -ti mbcorecr-validator sh -c "/root/.mbcorecr/mainuser.sh"
    responses:
      Enter\ your\ bip39\ mnemonic: "{{ mainuser_mnemonic }}"
      Enter\ keyring\ passphrase: "{{ keyring_pass }}"
      Re-enter\ keyring\ passphrase: "{{ keyring_pass }}"
  no_log: true
  tags:
    - valinit
    - ubnutu
    - register


- name: Add main validator creation script
  template:
    src: "create.sh"
    dest: "{{ project_dir }}/build/validator/create.sh"
    mode: '755'
  tags:
    - valinit
    - ubnutu
    - create

- name: Add validator
  expect:
    command: |
      docker exec -ti mbcorecr-validator sh -c "/root/.mbcorecr/create.sh"
    responses:
      Enter\ keyring\ passphrase: "{{ keyring_pass }}"
  no_log: true
  tags:
    - valinit
    - ubnutu
    - create