---
- hosts: testhost
  become: true
  vars:
    docker_users:
      - "{{ ansible_user }}"
  roles:
    - role: docker
  tasks:
    - name: reset ssh connection
      meta: reset_connection
 
      
