- name: Build node on a new machine
  hosts:
    - build
  become: yes
  roles:
    - role: docker
      tags:
      - install
    - build
  tasks:
    - name: reset ssh connection
      meta: reset_connection
  vars:
    docker_users:
      - "{{ ansible_user }}"
