- name: Add global variables
  include_vars:
    file: "{{ playbook_dir }}/config.yml"
  tags:
    - configs

- name: Create genesis validator account
  expect:
    command: |
      {{ project_dir }}/build/mbcorecrd keys add mainuser 
      --hd-path "44'/118'/0'/0/0" --home {{ project_dir }}/build/validator 
      --keyring-backend file --recover
    chdir: "{{ project_dir }}"
    responses:
      Enter\ your\ bip39\ mnemonic: "{{ mainuser_mnemonic }}"
      Enter\ keyring\ passphrase: "{{ keyring_pass }}"
      Re-enter\ keyring\ passphrase: "{{ keyring_pass }}"
  no_log: true
  tags:
    - init
    - ubnutu
    - genesis

- name: Read genesis addr to varible
  expect:
    command: |
      {{ project_dir }}/build/mbcorecrd keys show mainuser -a 
      --home {{ project_dir }}/build/validator --keyring-backend file
    chdir: "{{ project_dir }}"
    responses:
      Enter\ keyring\ passphrase: "{{ keyring_pass }}"
  no_log: true
  register: validator_address
  tags:
    - init
    - ubnutu
    - genesis

- name: Create genesis validator
  shell:
    cmd: |
        {{ project_dir }}/build/mbcorecrd add-genesis-account {{ validator_address.stdout_lines[1] }} \
        1000000000stake,20invitesuper,50invite0,50invite1,150invite2,150invite3 \
        --home {{ project_dir }}/build/validator
    chdir: "{{ project_dir }}"
  tags:
    - init
    - ubnutu
    - genesis

- name: Generate genesis transaction
  expect:
    command: |
        {{ project_dir }}/build/mbcorecrd gentx mainuser --from mainuser 
        --chain-id {{ chainid }} --amount {{ amount_to_delegate }}
        --home {{ project_dir }}/build/validator --keyring-backend file -y
    chdir: "{{ project_dir }}"
    responses:
      Enter\ keyring\ passphrase: "{{ keyring_pass }}"
  no_log: true
  tags:
    - init
    - ubnutu
    - genesis

- name: Collect genesis
  shell:
    cmd: |
        {{ project_dir }}/build/mbcorecrd collect-gentxs \
        --home {{ project_dir }}/build/validator 
    chdir: "{{ project_dir }}"
  no_log: false
  tags:
    - init
    - ubnutu
    - genesis

- name: Copy genesis file to other nodes
  copy:
    src: "{{ project_dir }}/build/validator/config/genesis.json"
    remote_src: yes
    dest: "{{ project_dir }}/build/{{ item }}/config/genesis.json"
  with_items:
    - sentery
    - seed
  tags:
    - init
    - ubnutu
    - genesis