// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crsign/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetAuthRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetAuthRequest) Reset()         { *m = QueryGetAuthRequest{} }
func (m *QueryGetAuthRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuthRequest) ProtoMessage()    {}
func (*QueryGetAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{0}
}
func (m *QueryGetAuthRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuthRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuthRequest.Merge(m, src)
}
func (m *QueryGetAuthRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuthRequest proto.InternalMessageInfo

func (m *QueryGetAuthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetAuthResponse struct {
	Auth *Auth `protobuf:"bytes,1,opt,name=Auth,proto3" json:"Auth,omitempty"`
}

func (m *QueryGetAuthResponse) Reset()         { *m = QueryGetAuthResponse{} }
func (m *QueryGetAuthResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuthResponse) ProtoMessage()    {}
func (*QueryGetAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{1}
}
func (m *QueryGetAuthResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuthResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuthResponse.Merge(m, src)
}
func (m *QueryGetAuthResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuthResponse proto.InternalMessageInfo

func (m *QueryGetAuthResponse) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type QueryGetId2ServiceRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetId2ServiceRequest) Reset()         { *m = QueryGetId2ServiceRequest{} }
func (m *QueryGetId2ServiceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetId2ServiceRequest) ProtoMessage()    {}
func (*QueryGetId2ServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{2}
}
func (m *QueryGetId2ServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetId2ServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetId2ServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetId2ServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetId2ServiceRequest.Merge(m, src)
}
func (m *QueryGetId2ServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetId2ServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetId2ServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetId2ServiceRequest proto.InternalMessageInfo

func (m *QueryGetId2ServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetId2ServiceResponse struct {
	Id2Service *Id2Service `protobuf:"bytes,1,opt,name=Id2Service,proto3" json:"Id2Service,omitempty"`
}

func (m *QueryGetId2ServiceResponse) Reset()         { *m = QueryGetId2ServiceResponse{} }
func (m *QueryGetId2ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetId2ServiceResponse) ProtoMessage()    {}
func (*QueryGetId2ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{3}
}
func (m *QueryGetId2ServiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetId2ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetId2ServiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetId2ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetId2ServiceResponse.Merge(m, src)
}
func (m *QueryGetId2ServiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetId2ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetId2ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetId2ServiceResponse proto.InternalMessageInfo

func (m *QueryGetId2ServiceResponse) GetId2Service() *Id2Service {
	if m != nil {
		return m.Id2Service
	}
	return nil
}

type QueryGetRecordRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetRecordRequest) Reset()         { *m = QueryGetRecordRequest{} }
func (m *QueryGetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecordRequest) ProtoMessage()    {}
func (*QueryGetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{4}
}
func (m *QueryGetRecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecordRequest.Merge(m, src)
}
func (m *QueryGetRecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecordRequest proto.InternalMessageInfo

func (m *QueryGetRecordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetRecordResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=Record,proto3" json:"Record,omitempty"`
}

func (m *QueryGetRecordResponse) Reset()         { *m = QueryGetRecordResponse{} }
func (m *QueryGetRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecordResponse) ProtoMessage()    {}
func (*QueryGetRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{5}
}
func (m *QueryGetRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecordResponse.Merge(m, src)
}
func (m *QueryGetRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecordResponse proto.InternalMessageInfo

func (m *QueryGetRecordResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type QueryGetId2RecordRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetId2RecordRequest) Reset()         { *m = QueryGetId2RecordRequest{} }
func (m *QueryGetId2RecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetId2RecordRequest) ProtoMessage()    {}
func (*QueryGetId2RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{6}
}
func (m *QueryGetId2RecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetId2RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetId2RecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetId2RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetId2RecordRequest.Merge(m, src)
}
func (m *QueryGetId2RecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetId2RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetId2RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetId2RecordRequest proto.InternalMessageInfo

func (m *QueryGetId2RecordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetId2RecordResponse struct {
	Id2Record *Id2Record `protobuf:"bytes,1,opt,name=Id2Record,proto3" json:"Id2Record,omitempty"`
}

func (m *QueryGetId2RecordResponse) Reset()         { *m = QueryGetId2RecordResponse{} }
func (m *QueryGetId2RecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetId2RecordResponse) ProtoMessage()    {}
func (*QueryGetId2RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f593c6c4e647fb, []int{7}
}
func (m *QueryGetId2RecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetId2RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetId2RecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetId2RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetId2RecordResponse.Merge(m, src)
}
func (m *QueryGetId2RecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetId2RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetId2RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetId2RecordResponse proto.InternalMessageInfo

func (m *QueryGetId2RecordResponse) GetId2Record() *Id2Record {
	if m != nil {
		return m.Id2Record
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetAuthRequest)(nil), "metabelarus.mbcorecr.crsign.QueryGetAuthRequest")
	proto.RegisterType((*QueryGetAuthResponse)(nil), "metabelarus.mbcorecr.crsign.QueryGetAuthResponse")
	proto.RegisterType((*QueryGetId2ServiceRequest)(nil), "metabelarus.mbcorecr.crsign.QueryGetId2ServiceRequest")
	proto.RegisterType((*QueryGetId2ServiceResponse)(nil), "metabelarus.mbcorecr.crsign.QueryGetId2ServiceResponse")
	proto.RegisterType((*QueryGetRecordRequest)(nil), "metabelarus.mbcorecr.crsign.QueryGetRecordRequest")
	proto.RegisterType((*QueryGetRecordResponse)(nil), "metabelarus.mbcorecr.crsign.QueryGetRecordResponse")
	proto.RegisterType((*QueryGetId2RecordRequest)(nil), "metabelarus.mbcorecr.crsign.QueryGetId2RecordRequest")
	proto.RegisterType((*QueryGetId2RecordResponse)(nil), "metabelarus.mbcorecr.crsign.QueryGetId2RecordResponse")
}

func init() { proto.RegisterFile("crsign/query.proto", fileDescriptor_a5f593c6c4e647fb) }

var fileDescriptor_a5f593c6c4e647fb = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x33, 0xc1, 0x16, 0x3a, 0x82, 0xe0, 0x54, 0xa5, 0xae, 0xb2, 0xe8, 0x8a, 0xc6, 0x36,
	0x74, 0xc7, 0x6c, 0x48, 0x3d, 0x78, 0x52, 0x84, 0xea, 0xc1, 0x83, 0x11, 0x2f, 0xde, 0x66, 0x77,
	0x87, 0xcd, 0x40, 0xb3, 0xb3, 0x9d, 0x99, 0x2d, 0x16, 0xf1, 0xe2, 0x5f, 0x20, 0x78, 0xf5, 0xe8,
	0xdd, 0x8b, 0xf8, 0x37, 0x78, 0x2c, 0x78, 0xf1, 0x28, 0x89, 0x7f, 0x88, 0x74, 0xe6, 0xad, 0xdd,
	0xd4, 0x74, 0x9b, 0x1c, 0xf3, 0xf8, 0xbe, 0xef, 0xfd, 0xf6, 0xe5, 0x63, 0x30, 0x49, 0x94, 0x16,
	0x59, 0x4e, 0xf7, 0x4b, 0xae, 0x0e, 0xc3, 0x42, 0x49, 0x23, 0xc9, 0x8d, 0x31, 0x37, 0x2c, 0xe6,
	0x7b, 0x4c, 0x95, 0x3a, 0x1c, 0xc7, 0x89, 0x54, 0x3c, 0x51, 0xa1, 0x13, 0x7a, 0x37, 0x33, 0x29,
	0xb3, 0x3d, 0x4e, 0x59, 0x21, 0x28, 0xcb, 0x73, 0x69, 0x98, 0x11, 0x32, 0xd7, 0xce, 0xea, 0x6d,
	0x25, 0x52, 0x8f, 0xa5, 0xa6, 0x31, 0xd3, 0xdc, 0x65, 0xd2, 0x83, 0x5e, 0xcc, 0x0d, 0xeb, 0xd1,
	0x82, 0x65, 0x22, 0xb7, 0x62, 0xd0, 0x5e, 0x86, 0xd5, 0xac, 0x34, 0x23, 0x18, 0xad, 0xc3, 0x48,
	0xf1, 0x44, 0xaa, 0xd4, 0x0d, 0x83, 0xbb, 0x78, 0xfd, 0xe5, 0x71, 0xd2, 0x2e, 0x37, 0x8f, 0x4b,
	0x33, 0x1a, 0xf2, 0xfd, 0x92, 0x6b, 0x43, 0x2e, 0xe1, 0xb6, 0x48, 0x37, 0xd0, 0x2d, 0x74, 0x7f,
	0x6d, 0xd8, 0x16, 0x69, 0xf0, 0x02, 0x5f, 0x99, 0x95, 0xe9, 0x42, 0xe6, 0x9a, 0x93, 0x01, 0xbe,
	0x70, 0xfc, 0xdb, 0x2a, 0x2f, 0x46, 0xb7, 0xc3, 0x86, 0x8f, 0x0b, 0xad, 0xd1, 0xca, 0x83, 0x2e,
	0xbe, 0x5e, 0xc5, 0x3d, 0x4f, 0xa3, 0x57, 0x5c, 0x1d, 0x88, 0x84, 0x9f, 0xb5, 0x9b, 0x63, 0x6f,
	0x9e, 0x18, 0x08, 0x76, 0x31, 0x3e, 0x99, 0x02, 0x47, 0xa7, 0x91, 0xa3, 0x16, 0x52, 0xb3, 0x06,
	0x1d, 0x7c, 0xb5, 0x5a, 0x33, 0xb4, 0x17, 0x3a, 0x8b, 0xe7, 0x35, 0xbe, 0x76, 0x5a, 0x08, 0x2c,
	0x8f, 0xf0, 0xaa, 0x9b, 0x00, 0xc7, 0x9d, 0x46, 0x0e, 0x30, 0x83, 0x25, 0xd8, 0xc2, 0x1b, 0xb5,
	0xcf, 0x6c, 0x46, 0x60, 0x33, 0xf7, 0x3b, 0x45, 0xf1, 0x14, 0xaf, 0xfd, 0x1b, 0x02, 0xc8, 0xbd,
	0xf3, 0x0e, 0x02, 0x11, 0x27, 0xc6, 0xe8, 0xfb, 0x0a, 0x5e, 0xb1, 0x3b, 0xc8, 0x67, 0xe4, 0xfe,
	0x64, 0xf2, 0xa0, 0x31, 0x65, 0x4e, 0x8d, 0xbc, 0xde, 0x12, 0x0e, 0x47, 0x1f, 0xd0, 0x0f, 0x3f,
	0xff, 0x7c, 0x6a, 0x6f, 0x92, 0x0e, 0xad, 0x59, 0x69, 0x65, 0xa5, 0xb5, 0x5a, 0x6b, 0xfa, 0x4e,
	0xa4, 0xef, 0xc9, 0x37, 0x54, 0x6f, 0x00, 0xd9, 0x59, 0x68, 0xe5, 0x7f, 0xad, 0xf3, 0x1e, 0x2e,
	0xed, 0x03, 0xe0, 0x81, 0x05, 0xa6, 0x64, 0xbb, 0x11, 0x58, 0xa4, 0x91, 0x76, 0x46, 0xc0, 0xfe,
	0x82, 0xaa, 0xb2, 0x90, 0x68, 0xa1, 0xd5, 0x33, 0x8d, 0xf0, 0xfa, 0x4b, 0x79, 0x00, 0xb5, 0x67,
	0x51, 0xbb, 0x64, 0xb3, 0x11, 0xd5, 0xbd, 0x0f, 0x80, 0xf9, 0x15, 0xd5, 0xda, 0x44, 0x06, 0x8b,
	0x1e, 0x69, 0x16, 0x76, 0x67, 0x59, 0x1b, 0xf0, 0xf6, 0x2d, 0xef, 0x36, 0xe9, 0x9e, 0x77, 0x5a,
	0x87, 0x6c, 0x89, 0x9f, 0x3c, 0xfb, 0x31, 0xf1, 0xd1, 0xd1, 0xc4, 0x47, 0xbf, 0x27, 0x3e, 0xfa,
	0x38, 0xf5, 0x5b, 0x47, 0x53, 0xbf, 0xf5, 0x6b, 0xea, 0xb7, 0xde, 0x84, 0x99, 0x30, 0xa3, 0x32,
	0x0e, 0x13, 0x39, 0x9e, 0x1f, 0xf8, 0xb6, 0x8a, 0x34, 0x87, 0x05, 0xd7, 0xf1, 0xaa, 0x7d, 0x22,
	0xfb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x01, 0xc7, 0xa8, 0x29, 0xc7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Auth(ctx context.Context, in *QueryGetAuthRequest, opts ...grpc.CallOption) (*QueryGetAuthResponse, error)
	Id2Service(ctx context.Context, in *QueryGetId2ServiceRequest, opts ...grpc.CallOption) (*QueryGetId2ServiceResponse, error)
	Record(ctx context.Context, in *QueryGetRecordRequest, opts ...grpc.CallOption) (*QueryGetRecordResponse, error)
	Id2Record(ctx context.Context, in *QueryGetId2RecordRequest, opts ...grpc.CallOption) (*QueryGetId2RecordResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Auth(ctx context.Context, in *QueryGetAuthRequest, opts ...grpc.CallOption) (*QueryGetAuthResponse, error) {
	out := new(QueryGetAuthResponse)
	err := c.cc.Invoke(ctx, "/metabelarus.mbcorecr.crsign.Query/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Id2Service(ctx context.Context, in *QueryGetId2ServiceRequest, opts ...grpc.CallOption) (*QueryGetId2ServiceResponse, error) {
	out := new(QueryGetId2ServiceResponse)
	err := c.cc.Invoke(ctx, "/metabelarus.mbcorecr.crsign.Query/Id2Service", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Record(ctx context.Context, in *QueryGetRecordRequest, opts ...grpc.CallOption) (*QueryGetRecordResponse, error) {
	out := new(QueryGetRecordResponse)
	err := c.cc.Invoke(ctx, "/metabelarus.mbcorecr.crsign.Query/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Id2Record(ctx context.Context, in *QueryGetId2RecordRequest, opts ...grpc.CallOption) (*QueryGetId2RecordResponse, error) {
	out := new(QueryGetId2RecordResponse)
	err := c.cc.Invoke(ctx, "/metabelarus.mbcorecr.crsign.Query/Id2Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Auth(context.Context, *QueryGetAuthRequest) (*QueryGetAuthResponse, error)
	Id2Service(context.Context, *QueryGetId2ServiceRequest) (*QueryGetId2ServiceResponse, error)
	Record(context.Context, *QueryGetRecordRequest) (*QueryGetRecordResponse, error)
	Id2Record(context.Context, *QueryGetId2RecordRequest) (*QueryGetId2RecordResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Auth(ctx context.Context, req *QueryGetAuthRequest) (*QueryGetAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedQueryServer) Id2Service(ctx context.Context, req *QueryGetId2ServiceRequest) (*QueryGetId2ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Id2Service not implemented")
}
func (*UnimplementedQueryServer) Record(ctx context.Context, req *QueryGetRecordRequest) (*QueryGetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (*UnimplementedQueryServer) Id2Record(ctx context.Context, req *QueryGetId2RecordRequest) (*QueryGetId2RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Id2Record not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metabelarus.mbcorecr.crsign.Query/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Auth(ctx, req.(*QueryGetAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Id2Service_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetId2ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Id2Service(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metabelarus.mbcorecr.crsign.Query/Id2Service",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Id2Service(ctx, req.(*QueryGetId2ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metabelarus.mbcorecr.crsign.Query/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Record(ctx, req.(*QueryGetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Id2Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetId2RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Id2Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metabelarus.mbcorecr.crsign.Query/Id2Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Id2Record(ctx, req.(*QueryGetId2RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metabelarus.mbcorecr.crsign.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Query_Auth_Handler,
		},
		{
			MethodName: "Id2Service",
			Handler:    _Query_Id2Service_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _Query_Record_Handler,
		},
		{
			MethodName: "Id2Record",
			Handler:    _Query_Id2Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crsign/query.proto",
}

func (m *QueryGetAuthRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuthRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuthRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuthResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuthResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuthResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Auth != nil {
		{
			size, err := m.Auth.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetId2ServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetId2ServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetId2ServiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetId2ServiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetId2ServiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetId2ServiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id2Service != nil {
		{
			size, err := m.Id2Service.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetId2RecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetId2RecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetId2RecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetId2RecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetId2RecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetId2RecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id2Record != nil {
		{
			size, err := m.Id2Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetAuthRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuthResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Auth != nil {
		l = m.Auth.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetId2ServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetId2ServiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id2Service != nil {
		l = m.Id2Service.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetId2RecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetId2RecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id2Record != nil {
		l = m.Id2Record.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetAuthRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuthRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuthRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuthResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuthResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuthResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Auth == nil {
				m.Auth = &Auth{}
			}
			if err := m.Auth.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetId2ServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetId2ServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetId2ServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetId2ServiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetId2ServiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetId2ServiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id2Service", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id2Service == nil {
				m.Id2Service = &Id2Service{}
			}
			if err := m.Id2Service.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &Record{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetId2RecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetId2RecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetId2RecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetId2RecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetId2RecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetId2RecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id2Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id2Record == nil {
				m.Id2Record = &Id2Record{}
			}
			if err := m.Id2Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
