---
- name: prevent docker related crashes in some cases
  apt:
    name:
      - gnupg2 
      - gpg
      - python3-pip
      - git
    state: present 
    update_cache: yes
  become: yes
- name: Install python packages
  pip:
    name:
      - docker
  become: yes
- name: Copy sourse from git
  git:
    repo: 'https://github.com/markvandal/metabelarus.core.cr.git'
    dest: ~/build/
    version: ops
- name: Add docker file
  copy:
    src: "Dockerfile"
    dest: "~/build/"
- name: Build mbcorecr docker image
  community.docker.docker_image:
    name: mbcorecrnode:latest
    build:
      path: "~/build/"
      cache_from: 
        - golang:alpine
    source: build
